# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dashboard.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dashboard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61shboard.proto\x12\x06icdash\"\\\n\rTrainingImage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12\x17\n\x0fpredicted_label\x18\x03 \x01(\t\x12\x12\n\ntrue_label\x18\x04 \x01(\t\"d\n\rTrainingBatch\x12\x11\n\titeration\x18\x01 \x01(\x05\x12%\n\x06images\x18\x02 \x03(\x0b\x32\x15.icdash.TrainingImage\x12\x0c\n\x04loss\x18\x03 \x01(\x02\x12\x0b\n\x03\x66ps\x18\x04 \x01(\x02\"\x07\n\x05\x45mpty\"\"\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\tHeartbeat\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x03\x32r\n\x10\x44\x61shboardService\x12\x36\n\x0eStreamTraining\x12\x15.icdash.TrainingBatch\x1a\x0b.icdash.Ack(\x01\x12&\n\x04Ping\x12\x11.icdash.Heartbeat\x1a\x0b.icdash.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dashboard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAININGIMAGE']._serialized_start=27
  _globals['_TRAININGIMAGE']._serialized_end=119
  _globals['_TRAININGBATCH']._serialized_start=121
  _globals['_TRAININGBATCH']._serialized_end=221
  _globals['_EMPTY']._serialized_start=223
  _globals['_EMPTY']._serialized_end=230
  _globals['_ACK']._serialized_start=232
  _globals['_ACK']._serialized_end=266
  _globals['_HEARTBEAT']._serialized_start=268
  _globals['_HEARTBEAT']._serialized_end=301
  _globals['_DASHBOARDSERVICE']._serialized_start=303
  _globals['_DASHBOARDSERVICE']._serialized_end=417
# @@protoc_insertion_point(module_scope)
