# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import dashboard_pb2 as dashboard__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dashboard_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DashboardServiceStub(object):
    """---------------- SERVICE ----------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTraining = channel.stream_unary(
                '/icdash.DashboardService/StreamTraining',
                request_serializer=dashboard__pb2.TrainingBatch.SerializeToString,
                response_deserializer=dashboard__pb2.Ack.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/icdash.DashboardService/Ping',
                request_serializer=dashboard__pb2.Heartbeat.SerializeToString,
                response_deserializer=dashboard__pb2.Ack.FromString,
                _registered_method=True)


class DashboardServiceServicer(object):
    """---------------- SERVICE ----------------

    """

    def StreamTraining(self, request_iterator, context):
        """Main RPC: the training process streams batches to the dashboard.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Optional: simple ping to check connectivity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DashboardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTraining': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTraining,
                    request_deserializer=dashboard__pb2.TrainingBatch.FromString,
                    response_serializer=dashboard__pb2.Ack.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=dashboard__pb2.Heartbeat.FromString,
                    response_serializer=dashboard__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'icdash.DashboardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('icdash.DashboardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DashboardService(object):
    """---------------- SERVICE ----------------

    """

    @staticmethod
    def StreamTraining(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/icdash.DashboardService/StreamTraining',
            dashboard__pb2.TrainingBatch.SerializeToString,
            dashboard__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icdash.DashboardService/Ping',
            dashboard__pb2.Heartbeat.SerializeToString,
            dashboard__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
